version: '3.9'
services:
  nginx:
    image: nginx:1.21-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ../:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: app
      target: develop
    volumes:
      - ../:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_NAME}
  db:
    image: postgres:14-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  db:
    name: ${COMPOSE_PROJECT_NAME}_db
